version: "3"
services:
  prep-node:
     image: "iconloop/prep-node"
     container_name: "prep-testnet"
     network_mode: host
     restart: "on-failure"
     environment:
        SERVICE: "zicon"
        LOG_OUTPUT_TYPE: "file"
        CERT_PATH: "/cert"
        LOOPCHAIN_LOG_LEVEL: "DEBUG"
        ICON_LOG_LEVEL: "DEBUG"
        FASTEST_START: "yes" # Restore from lastest snapshot DB
        PRIVATE_KEY_FILENAME: "keystore-file" # only file name
        PRIVATE_PASSWORD: "keystore-password"
     cap_add:
        - SYS_TIME
     volumes:
        - ./data:/data # mount a data volumes
        - ./cert:/cert # Automatically generate cert key files here
     ports:
         - 7100:7100
         - 9000:9000
